[connections.faq_db]
dialect = "mysql"
username = "faq_user"
password = "faq1234"
host = "127.0.0.1"
database = "faq_db" 

[connections.mydb]
dialect = "mysql"
username = "team"
password = "1234"
host = "localhost"
database = "자동차현황"